MVCTraining/Areas/Admin/Controllers/Homework2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCTraining.Models;
using MVCTraining.Service;
using MVCTraining.Repositories;
using MVCTraining.ViewModels;
using NLog;
using MVCTraining.Enums;
using MVCTraining.Filers;
using System.Net;

namespace MVCTraining.Areas.Admin.Controllers
{
    [AuthorizePlus(IsAdminOnly=true, RejectedToUrl = "/Home")]
    public class Homework2Controller : Controller
    {
        private readonly TrackSpendingService _trackSpendingService;
        private static Logger logger = NLog.LogManager.GetCurrentClassLogger();
        private readonly EnumList enumList = new EnumList();

        public Homework2Controller()
        {
            var unitOfWork = new EFUnitOfWork();
            _trackSpendingService = new TrackSpendingService(unitOfWork);
        }

        // GET: Admin/Homework2
        public ActionResult Index()
        {
            var model = new TrackSpendingViewModel2()
            {
                CategoryList = new SelectList(enumList.GetCategoryyyList(), "value", "name")
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AjaxAction(TrackSpendingViewModel2 viewModel2)
        {
            if (ModelState.IsValid)
            {
                if (viewModel2.Id == Guid.Empty)
                {
                    //create
                    var accountBook = new AccountBook()
                    {
                        Amounttt = viewModel2.Amounttt,
                        Categoryyy = viewModel2.Categoryyy,
                        Dateee = viewModel2.Dateee,
                        Remarkkk = viewModel2.Remarkkk
                    };

                    _trackSpendingService.Add(accountBook);
                    _trackSpendingService.Save();

                    return View("ForIndexChild", _trackSpendingService.GetAll());
                }
                else
                {
                    //edit
                    _trackSpendingService.Edit(viewModel2);
                    _trackSpendingService.Save();

                    return View("ForIndexChild", _trackSpendingService.GetAll());
                }
            }

            return View("ForIndexChild");
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var result = _trackSpendingService.GetSingle(id);
            result.CategoryList = new SelectList(enumList.GetCategoryyyList(), "value", "name");

            return View("Index", result);
        }

        [ChildActionOnly]
        public ActionResult ForIndexChild()
        {
            return View(_trackSpendingService.GetAll());
        }
    }
}

MVCTraining/Controllers/Homework2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCTraining.Models;
using MVCTraining.Service;
using MVCTraining.Repositories;
using MVCTraining.ViewModels;
using PagedList;
using NLog;
using MVCTraining.Enums;

namespace MVCTraining.Controllers
{
    public class Homework2Controller : Controller
    {
        private readonly TrackSpendingService _trackSpendingService;
        private static Logger logger = NLog.LogManager.GetCurrentClassLogger();
        private readonly EnumList enumList = new EnumList();

        public Homework2Controller()
        {
            var unitOfWork = new EFUnitOfWork();
            _trackSpendingService = new TrackSpendingService(unitOfWork);
        }

        // GET: Homework2
        public ActionResult Index()
        {
            var model = new TrackSpendingViewModel2()
            {
                CategoryList = new SelectList(enumList.GetCategoryyyList(), "value", "name")
            };
            return View(model);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        ////public ActionResult Index([Bind(Include = "Amounttt, Categoryyy, Dateee, Remarkkk")] AccountBook accountBook)
        ////上面寫法會不會通過寫在TrackSpendingViewModel2的自訂ValidationAttribute
        //public ActionResult Index(TrackSpendingViewModel2 viewModel2)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var accountBook = new AccountBook()
        //        {
        //            Amounttt = viewModel2.Amounttt,
        //            Categoryyy = viewModel2.Categoryyy,
        //            Dateee = viewModel2.Dateee,
        //            Remarkkk = viewModel2.Remarkkk
        //        };

        //        _trackSpendingService.Add(accountBook);
        //        _trackSpendingService.Save();

        //        return RedirectToAction("Index");
        //    }

        //    viewModel2.CategoryList = new SelectList(enumList.GetCategoryyyList(), "value", "name");

        //    return View(viewModel2);
        //}

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult AjaxAction(TrackSpendingViewModel2 viewModel2)
        {
            if (ModelState.IsValid)
            {
                var accountBook = new AccountBook()
                {
                    Amounttt = viewModel2.Amounttt,
                    Categoryyy = viewModel2.Categoryyy,
                    Dateee = viewModel2.Dateee,
                    Remarkkk = viewModel2.Remarkkk
                };

                _trackSpendingService.Add(accountBook);
                _trackSpendingService.Save();

                return View("ForIndexChild", _trackSpendingService.GetAll());
            }

            return View("ForIndexChild");
        }

        [ChildActionOnly]
        public ActionResult ForIndexChild()
        {
            return View(_trackSpendingService.GetAll());
        }

        public ActionResult SSOLogin()
        {
            Uri uri = HongHwa.Settings.SsoWebDevelop;
            string url = uri.AbsoluteUri;

            return Redirect(url);
        }

        public ActionResult SSOLogout()
        {

            return Redirect(HongHwa.Settings.SsoWebDevelopLogout.AbsoluteUri);
        }

        
    }
}

MVCTraining/Views/Homework2/ForIndexChild.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IEnumerable<MVCTraining.ViewModels.TrackSpendingViewModel2>

@{
    Layout = null;
    var area = ViewContext.RouteData.DataTokens["area"];
    string CurrentArea = area == null ? "" : area.ToString();
}

<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover">
            <tr>
                <th>#</th>
                <th>類別</th>
                <th>日期</th>
                <th>金額</th>
                @if (User.IsInRole("管理者") && CurrentArea.Equals("Admin"))
                {
                    <th>異動</th>
                }
            </tr>

            @{
                var i = 1;
                foreach (var item in Model)
                {
                    var categoryName = item.Categoryyy == 1 ? "支出" : "收入";
                    var categoryColor = item.Categoryyy == 1 ? "red" : "blue";
                    <tr>
                        <td>
                            @(i)
                        </td>
                        <td>
                            <span style="color:@(categoryColor);">@(categoryName)</span>
                        </td>
                        <td>
                            @(item.Dateee.ToString("yyyy-MM-dd"))
                        </td>
                        <td>
                            @(String.Format("{0:#,0}", item.Amounttt))
                        </td>
                        @if (User.IsInRole("管理者") && CurrentArea.Equals("Admin"))
                        {
                            <td><a href="@Url.Action("Edit", "Homework2", new { area = "Admin", id= item.Id})">修改</a></td>
                        }
                    </tr>
                    i++;
                }
            }

        </table>

    </div>
</div>

MVCTraining/Views/Homework2/Index.cshtml
@model MVCTraining.ViewModels.TrackSpendingViewModel2

@{
    ViewBag.Title = "我的記賬本";
    var actionName = ViewContext.RouteData.Values["action"];

}

<div class="well">
    @if (User.Identity.IsAuthenticated)
    {
        using (Ajax.BeginForm(new AjaxOptions()
        {
            HttpMethod = "Post",
            UpdateTargetId = "ajax-result",
            Url = Url.Action("AjaxAction"),
            OnSuccess = "cleanInput"

        }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()
            @Html.HiddenFor(model=>model.Id)
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.Label("Category", "類別", new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-10">
                        @Html.DropDownListFor(model => model.Categoryyy, Model.CategoryList, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Categoryyy, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Amounttt, "金額", new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Amounttt, new { htmlAttributes = new { @class = "form-control", @placeHolder = "金額" } })
                        @Html.ValidationMessageFor(model => model.Amounttt, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Dateee, "日期", new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Dateee, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control datepicker",
                           @placeholder = "日期",
                           @autocomplete = "off"
                       }
                   })
                        @Html.ValidationMessageFor(model => model.Dateee, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Remarkkk, "備註", new { @class = "col-sm-2 control-label" })
                    <div class="col-sm-10">
                        @Html.TextAreaFor(model => model.Remarkkk, new { @class = "form-control", @maxLength = 100 })
                        @Html.ValidationMessageFor(model => model.Remarkkk, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-8 col-sm-4">
                        <button id="btn" type="submit" class="btn btn-default">送出</button>
                    </div>
                </div>
            </div>
        }
    }else
    {
        <h3>需 <a href="@Url.Action("Login", "Account")">登入</a> 才可輸入資料</h3>
        <div class="alert alert-danger">
            Admin預設帳號：<code>ZA2387</code>
            <br />
            user預設帳號：<code>ZA4234</code>
        </div>
    }
</div>

@*在送出後資料驗證部分遇到障礙，須將填寫表單以及列表的Model分開，故將Partial改成ChildAction *@
@if (true)//actionName.Equals("Edit") == false
{
    <div id="ajax-result">
        @Html.Action("ForIndexChild")
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datepicker")
    @Scripts.Render("~/bundles/numpad")
    @Scripts.Render("~/bundles/ajax")

    <script type="text/javascript">
        $.validator.addMethod("datecheck", function (value, element) {
            if (value == false) {
                return true;
            }

            var now = $.now();
            if (now < Date.parse(value)) {
                return false;
            }
            return true;
        });
        //有設定參數addSingleVal
        //單純判斷條件addBool
        $.validator.unobtrusive.adapters.addBool("datecheck");

        //數字鍵盤
        $(function () {
            $("#Amounttt").numpad({
                hidePlusMinusButton: true,
                hideDecimalButton: true,
                onKeypadClose: function () {
                    $("#Amounttt").focus();
                    $("#Amounttt").blur();
                }
            });
        });

        function cleanInput() {
            $("form").find("input:not([name='__RequestVerificationToken']) , textarea").val("");
        }
    </script>
}