MVCTraining/Controllers/Homework1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCTraining.Models;
using MVCTraining.ViewModels;
using Newtonsoft.Json;

namespace MVCTraining.Controllers
{
    public class Homework1Controller : Controller
    {
        // GET: Homework1
        public ActionResult Index()
        {
            //假資料
            var defaultList = new List<TrackSpending> 
            {
                new TrackSpending{ Category = 1 ,Money = 300, Date = new DateTime(2016, 01, 01)},
                new TrackSpending{ Category = 1 ,Money = 16000, Date = new DateTime(2016, 01, 02)},
                new TrackSpending{ Category = 1 ,Money = 8000, Date = new DateTime(2016, 01, 03)}
            };

            var model = new TrackSpendingViewModel
            {
                List = defaultList,
                ListJSON = JsonConvert.SerializeObject(defaultList)
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(TrackSpendingViewModel paraData)
        {
            var list = JsonConvert.DeserializeObject<List<TrackSpending>>(paraData.ListJSON);
            var track = new TrackSpending
            {
                Category = paraData.TrackSpending.Category,
                Money = paraData.TrackSpending.Money,
                Date = paraData.TrackSpending.Date,
                Description = paraData.TrackSpending.Description

            };
            list.Add(track);
            var model = new TrackSpendingViewModel
            {
                List = list,
                ListJSON = JsonConvert.SerializeObject(list)

            };
            return View(model);
        }
    }
}

MVCTraining/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡人", "Contact", "Home")</li>
                    <li>@Html.ActionLink("作業1", "Index", "Homework1")</li>*@
                    <li>@Html.ActionLink("作業", "Index", new { controller = "Homework2", area = "" })</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("管理", "Index", new { controller = "Homework2", area = "Admin" })</li>
                    }
                </ul>
                @*<ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("SSO登入", "SSOLogin", "Homework2")</li>
                        <li>@Html.ActionLink("SSO登出", "SSOLogout", "Homework2")</li>
                    </ul>*@
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        var alertMsg = "@TempData["AlertMsg"]";

        if (alertMsg != "") {
            alert(alertMsg);
        }

    </script>
</body>
</html>